// 饮料配置
// Excel 函数 =CONCATENATE("{'name':'",B2,"', 'chinese':'",A2,"', 'tag': '",E2,"', 'level':'",C2,"', 'money': '",D2,"'},")

export const drinksData = () => {
    return [
        {"name":"lc", "chinese":"绿茶", "tag": "无酒精", "level":"1", "money": "1"},
        {"name":"qj", "chinese":"雀酒", "tag": "中酒精,可加冰,可加热,清酒,辛", "level":"2", "money": "50"},
        {"name":"gwhb", "chinese":"果味High Ball", "tag": "低酒精,可加冰,鸡尾酒,西洋酒,水果,甘,苦", "level":"1", "money": "12"},
        {"name":"gws", "chinese":"果味SOUR", "tag": "低酒精,可加冰,烧酒,鸡尾酒,水果,甘,苦", "level":"1", "money": "12"},
        {"name":"q", "chinese":"淇", "tag": "低酒精,可加冰,清酒,鸡尾酒,气泡,甘,辛,苦", "level":"1", "money": "18"},
        {"name":"stj", "chinese":"水獭祭", "tag": "中酒精,可加冰,可加热,清酒,直饮", "level":"3", "money": "130"},
        {"name":"dbge", "chinese":"大冰棍儿", "tag": "无酒精,提神,甘,现代", "level":"2", "money": "35"},
        {"name":"bsmydn", "chinese":"冰山毛玉冻柠", "tag": "无酒精,直饮,气泡,提神,可加冰,甘,水果", "level":"2", "money": "45"},
        {"name":"mj", "chinese":"梅酒", "tag": "中酒精,可加冰,可加热,利口酒,水果", "level":"2", "money": "32"},
        {"name":"bzqs", "chinese":"波子汽水", "tag": "无酒精,气泡,现代", "level":"2", "money": "30"},
        {"name":"ryx", "chinese":"日月星", "tag": "中酒精,可加冰,可加热,清酒,直饮", "level":"2", "money": "34"},
        {"name":"czpj", "chinese":"超ZUN啤酒", "tag": "低酒精,可加冰,啤酒,苦", "level":"1", "money": "18"},
        {"name":"xhem", "chinese":"猩红恶魔", "tag": "低酒精,可加冰,鸡尾酒,西洋酒", "level":"2", "money": "45"},
        {"name":"dn", "chinese":"冬酿", "tag": "低酒精,甘,可加热,可加冰,古典", "level":"2", "money": "60"},
        {"name":"hsq", "chinese":"火鼠裘", "tag": "高酒精,可加热,辛,烧酒", "level":"4", "money": "420"},
        {"name":"tgy", "chinese":"天狗踊", "tag": "高酒精,可加冰,可加热,清酒,直饮", "level":"2", "money": "70"},
        {"name":"x", "chinese":"晓", "tag": "高酒精,可加冰,西洋酒,直饮", "level":"4", "money": "400"},
        {"name":"fz", "chinese":"风祝", "tag": "中酒精,可加冰,鸡尾酒,甘,现代", "level":"3", "money": "130"},
        {"name":"ngln", "chinese":"尼格罗尼", "tag": "中酒精,鸡尾酒,可加冰,水果,苦,西洋酒", "level":"3", "money": "100"},
        {"name":"jf", "chinese":"教父", "tag": "高酒精,可加冰,鸡尾酒,西洋酒,苦,古典", "level":"3", "money": "180"},
        {"name":"ylc", "chinese":"玉露茶", "tag": "无酒精,古典,可加热", "level":"2", "money": "50"},
        {"name":"ymhj", "chinese":"月面火箭", "tag": "无酒精,可加冰,现代,气泡", "level":"2", "money": "45"},
        {"name":"ssy", "chinese":"十四夜", "tag": "中酒精,清酒,可加冰,可加热,古典,甘", "level":"4", "money": "440"},
        {"name":"szm", "chinese":"神之麦", "tag": "中酒精,可加冰,可加热,烧酒,直饮", "level":"2", "money": "45"},
        {"name":"afjd", "chinese":"阿芙加朵", "tag": "无酒精,提神,甘,苦,可加冰", "level":"2", "money": "35"},
        {"name":"hw", "chinese":"红雾", "tag": "中酒精,可加热,西洋酒", "level":"2", "money": "75"},
        {"name":"hmghc", "chinese":"红魔馆红茶", "tag": "无酒精,水果,可加热,提神", "level":"2", "money": "25"},
        {"name":"nn", "chinese":"牛奶", "tag": "无酒精,直饮", "level":"2", "money": "16"},
        {"name":"hygz", "chinese":"红柚果汁", "tag": "无酒精,水果", "level":"2", "money": "24"},
        {"name":"dyn", "chinese":"大吟酿", "tag": "中酒精,清酒,水果,可加冰,直饮,甘,古典", "level":"3", "money": "210"},
        {"name":"kf", "chinese":"咖啡", "tag": "无酒精,苦,现代,可加热,可加冰,提神", "level":"2", "money": "62"},
        {"name":"gfnybs", "chinese":"古法奶油冰沙", "tag": "无酒精,甘,可加冰,古典", "level":"1", "money": "42"},
        {"name":"ptjsc", "chinese":"普通健身茶", "tag": "中酒精,苦,气泡,利口酒", "level":"2", "money": "32"},
        {"name":"yjyl", "chinese":"妖精雨露", "tag": "无酒精,甘,可加冰", "level":"2", "money": "80"},
        {"name":"gs", "chinese":"鬼杀", "tag": "高酒精,可加冰,烧酒,辛,古典", "level":"4", "money": "320"},
        {"name":"gmdbjl", "chinese":"古明地冰激凌", "tag": "无酒精,甘,水果,现代", "level":"2", "money": "35"},
        {"name":"qbj", "chinese":"气保健", "tag": "无酒精,甘,直饮,提神", "level":"2", "money": "45"},
        {"name":"ql", "chinese":"麒麟", "tag": "中酒精,啤酒,直饮", "level":"3", "money": "180"},
        {"name":"yzgl", "chinese":"杨枝甘露", "tag": "无酒精,可加冰,水果", "level":"2", "money": "50"},
        {"name":"lrz", "chinese":"伶人醉", "tag": "低酒精,直饮,水果,古典,甘", "level":"3", "money": "100"},
        {"name":"tdwy", "chinese":"天地无用", "tag": "高酒精,烧酒", "level":"3", "money": "150"},
        {"name":"mjtbjq", "chinese":"莫吉托爆浆球", "tag": "低酒精,气泡,现代,鸡尾酒", "level":"4", "money": "300"},
        {"name":"hdne", "chinese":"海的女儿", "tag": "低酒精,气泡,辛,古典", "level":"3", "money": "80"},
        {"name":"tkpj", "chinese":"太空啤酒", "tag": "中酒精,现代,水果,啤酒", "level":"3", "money": "42"},
        {"name":"mjkf", "chinese":"魔界咖啡", "tag": "高酒精,提神,可加热,西洋酒", "level":"4", "money": "210"},
        {"name":"wxbkf", "chinese":"卫星冰咖啡", "tag": "无酒精,现代,提神,苦", "level":"3", "money": "96"}
    ]
}